/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void dicerollMethodTest() {
        Library sut = new Library();
        System.out.println("Die rolls: " + Arrays.toString(sut.roll(6)));
    }
    @Test void checkduplicatedMethodTest() {
        Library sut = new Library();
        int[] arr = {1,2,3,1};
        assertTrue(sut.containsDuplicates(arr),"checks if there duplacates");
    }

    @Test void someAvgMethod() {

    }
    @Test void someLowArrAvgMethod() {

    }
}
