/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class Library {
    public static void main(String[] args) {

    }



    public boolean someLibraryMethod() {
        return true;
    }


//Rolling Dice feature
    public  int[] roll(int n){
        Random rand = new Random();
        int[] timesRolled = new int[n];

        for (int i = 0; i < n; i++) {
            int randoNum = rand.nextInt(6);
            timesRolled[i] = randoNum + 1;
        }
        return timesRolled;

    }
// checking duplicates
    public boolean containsDuplicates (int[] arr) {
        for (int i = 0; i < arr.length; i++){
            for (int j = 1; j < arr.length; j++){
                if (i == j) continue;
                if (arr[i] == arr[j])
                    return true;
            }
        }
        return false;
    }
// getting average
    public double average (int[] arr){
        int num = 0;
        for(int ele : arr) {
            num += ele;
        }
        double results = (double)num / arr.length;
        return results;
    }

   public int[] lowestArrAverage(int[] []arr) {
        int num = 0;
        double lowAvg = average(arr[0]);
        double currentAvg = lowAvg;
        for (int i=0 ; i < arr.length; i++){
            currentAvg = average(arr[i]);
            if(currentAvg < lowAvg) {
                lowAvg = currentAvg;
                num = i;
            }
        }
       return arr[num];
   }




}





