/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import inheritance.Review.Restaurantreview;
import inheritance.Business.Restaurant;
import inheritance.Review.TheaterReview;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class inheritanceTest {
    Restaurant newRestaurant = new Restaurant("Jubba", "$");
    Restaurantreview newReview = new Restaurantreview("Abdulahi", "Was dirty and nasty", 1);
    Restaurantreview newReview2 = new Restaurantreview("Bill", "best food in the city", 5);

    @Test
    void restaurantConsNamePrice_test() {
        assertTrue(newRestaurant.name == "Jubba");
        assertTrue(newRestaurant.price == "$");
    }

    @Test
    void ResturantData_test() {
        assertEquals("Jubba $ 0" ,newRestaurant.toString());
    }

    @Test
    void reviewConstInput_test() {
        assertTrue(newReview.author == "Abdulahi");
        assertTrue(newReview.notes == "Was dirty and nasty");
        assertTrue(newReview.numStar == 1);
    }

    @Test
    void ReviewString_test() {
        assertEquals("Abdulahi Was dirty and nasty 1", newReview.toString());
    }

    @Test
    void ResArrayUpdate_test() {
        newRestaurant.addReview(newReview);
        Restaurantreview checkReview = (Restaurantreview) newRestaurant.reviewList.get(0);
        assertEquals("Abdulahi Was dirty and nasty 1", checkReview.toString());
    }

    @Test
    void numstars_test() {
        newRestaurant.addReview(newReview);
        newRestaurant.addReview(newReview2);
        assertEquals(3, newRestaurant.numStar);
    }

    @Test
    void no_movieName_test() {
        TheaterReview sut = new TheaterReview("AMC", "coool theater",3);
        System.out.println(sut.movieName);
        assertTrue(true, "Yo something is wrong with test_getMovies()");
    }

}